projects:
  tijolinhoBackEnd:
    schemaPath: amplify/backend/api/tijolinhoBackEnd/build/schema.graphql
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        maxDepth: 3
extensions:
  amplify:
    version: 3
