/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:67b9cf7f-8398-4483-8b11-066c17d4bc30",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_5oRsnJPzo",
    "aws_user_pools_web_client_id": "6l454rrblh0s3jri4c4nuqg4of",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ooxmhg7tcrb3zmx2naoeuwypry.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
