/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:67b9cf7f-8398-4483-8b11-066c17d4bc30",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_SDlF6s8aK",
    "aws_user_pools_web_client_id": "6ksig5otk0a4esag65s2eu6qh3",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://pzzzbnonbbcnzlmh5pd2rdyc6m.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
